// Mock data compatível com a estrutura da API do backend
export default {
  purchaseOrders: [
    {
      id: 1,
      code: 'PO-2024-001',
      supplier_id: 1,
      supplier: { id: 1, name: 'Alcoa Brasil', country: 'Brasil' },
      quantity_tons: 1200,
      aluminum_type: 'Alumínio Primário P1020',
      expected_delivery_date: '2024-02-15',
      expected_payment_date: '2024-02-20',
      payment_terms: '30 dias',
      currency: 'USD',
      status: 'submitted',
      location_id: 1,
      avg_cost: 2450.00,
      arrival_date: '2024-02-15',
      created_at: '2024-01-10T10:00:00Z',
    },
    {
      id: 2,
      code: 'PO-2024-002',
      supplier_id: 2,
      supplier: { id: 2, name: 'Hydro Alumínio', country: 'Brasil' },
      quantity_tons: 850,
      aluminum_type: 'Liga de Alumínio 6061',
      expected_delivery_date: '2024-03-01',
      currency: 'USD',
      status: 'hedged',
      location_id: 1,
      avg_cost: 2580.00,
      created_at: '2024-01-12T14:30:00Z',
    },
  ],
  
  salesOrders: [
    {
      id: 1,
      code: 'SO-2024-001',
      customer_id: 1,
      customer: { id: 1, name: 'Embraer', country: 'Brasil' },
      quantity_tons: 950,
      aluminum_type: 'Alumínio Primário P1020',
      expected_delivery_date: '2024-03-15',
      expected_receipt_date: '2024-03-20',
      currency: 'USD',
      status: 'submitted',
      location_id: 1,
      created_at: '2024-01-15T09:00:00Z',
    },
    {
      id: 2,
      code: 'SO-2024-002',
      customer_id: 2,
      customer: { id: 2, name: 'ArcelorMittal Brasil', country: 'Brasil' },
      quantity_tons: 1500,
      aluminum_type: 'Liga de Alumínio 6061',
      expected_delivery_date: '2024-04-10',
      currency: 'USD',
      status: 'hedged',
      location_id: 2,
      created_at: '2024-01-18T11:30:00Z',
    },
  ],

  suppliers: [
    { id: 1, name: 'Alcoa Brasil', country: 'Brasil', contact: 'comercial@alcoa.com.br' },
    { id: 2, name: 'Hydro Alumínio', country: 'Brasil', contact: 'vendas@hydro.com' },
    { id: 3, name: 'CBA - Companhia Brasileira de Alumínio', country: 'Brasil', contact: 'suprimentos@cba.com.br' },
    { id: 4, name: 'Novelis', country: 'Brasil', contact: 'comercial@novelis.com' },
  ],

  customers: [
    { id: 1, name: 'Embraer', country: 'Brasil', contact: 'compras@embraer.com.br' },
    { id: 2, name: 'ArcelorMittal Brasil', country: 'Brasil', contact: 'procurement@arcelormittal.com' },
    { id: 3, name: 'Volkswagen do Brasil', country: 'Brasil', contact: 'suprimentos@vw.com.br' },
    { id: 4, name: 'Mercedez-Benz Brasil', country: 'Brasil', contact: 'purchasing@mercedes-benz.com.br' },
  ],

  counterparties: [
    {
      id: 1,
      name: 'Banco Itaú BBA',
      contact_email: 'mesa.commodities@itau.com.br',
      contact_phone: '+55 11 3708-8000',
      preferred_channel: 'api',
      credit_limit: 50000000,
      credit_limit_currency: 'USD',
      active: true,
      created_at: '2023-01-10T10:00:00Z',
    },
    {
      id: 2,
      name: 'BTG Pactual',
      contact_email: 'derivativos@btgpactual.com',
      contact_phone: '+55 11 3383-2000',
      preferred_channel: 'api',
      credit_limit: 75000000,
      credit_limit_currency: 'USD',
      active: true,
      created_at: '2023-02-15T14:30:00Z',
    },
    {
      id: 3,
      name: 'Santander Corretora',
      contact_email: 'mesa.metais@santander.com.br',
      contact_phone: '+55 11 3553-3300',
      preferred_channel: 'email',
      credit_limit: 40000000,
      credit_limit_currency: 'USD',
      active: true,
      created_at: '2023-03-20T09:15:00Z',
    },
  ],

  rfqs: [
    {
      id: 1,
      rfq_type: 'hedge_buy',
      reference_po_id: 1,
      tenor_month: 'Mar-24',
      quantity_tons: 1200,
      channel: 'api',
      status: 'quoted',
      sent_at: '2024-01-10T15:00:00Z',
      created_at: '2024-01-10T14:30:00Z',
      quotes: [
        {
          id: 1,
          rfq_id: 1,
          provider: 'Banco Itaú BBA',
          price: 2450.00,
          fee_bps: 15,
          currency: 'USD',
          selected: true,
          created_at: '2024-01-10T16:00:00Z',
        },
        {
          id: 2,
          rfq_id: 1,
          provider: 'BTG Pactual',
          price: 2455.00,
          fee_bps: 12,
          currency: 'USD',
          selected: false,
          created_at: '2024-01-10T16:15:00Z',
        },
      ],
    },
  ],

  hedges: [
    {
      id: 1,
      hedge_type: 'purchase',
      side: 'buy',
      lme_contract: 'LME-AL',
      contract_month: 'Mar-24',
      expiry_date: '2024-03-15',
      lots: 48,
      lot_size_tons: 25,
      price: 2450.00,
      currency: 'USD',
      notional_tons: 1200,
      status: 'executed',
      purchase_order_id: 1,
      executed_at: '2024-01-10T17:00:00Z',
      created_at: '2024-01-10T16:30:00Z',
    },
  ],

  locations: [
    { id: 1, name: 'Santos - SP', active: true, created_at: '2023-01-01T00:00:00Z' },
    { id: 2, name: 'Paranaguá - PR', active: true, created_at: '2023-01-01T00:00:00Z' },
    { id: 3, name: 'Rio de Janeiro - RJ', active: true, created_at: '2023-01-01T00:00:00Z' },
    { id: 4, name: 'São Paulo - SP (Armazém)', active: true, created_at: '2023-01-01T00:00:00Z' },
  ],
};
